#############################################################################
# Makefile for building: YellowShark
# Generated by qmake (2.01a) (Qt 4.8.2) on: dim. nov. 22 18:46:57 2015
# Project:  YellowShark.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile YellowShark.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -std=c++11 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -L/opt/local/lib/ -lpcap -lc -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		pcap_analyse.cpp \
		paquet.cpp \
		sendpacketwindow.cpp \
		tools.cpp \
		filterwindow.cpp \
		live_analyse.cpp moc_mainwindow.cpp \
		moc_pcap_analyse.cpp \
		moc_sendpacketwindow.cpp \
		moc_filterwindow.cpp \
		moc_live_analyse.cpp
OBJECTS       = main.o \
		mainwindow.o \
		pcap_analyse.o \
		paquet.o \
		sendpacketwindow.o \
		tools.o \
		filterwindow.o \
		live_analyse.o \
		moc_mainwindow.o \
		moc_pcap_analyse.o \
		moc_sendpacketwindow.o \
		moc_filterwindow.o \
		moc_live_analyse.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		YellowShark.pro
QMAKE_TARGET  = YellowShark
DESTDIR       = 
TARGET        = YellowShark

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_sendpacketwindow.h ui_filterwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: YellowShark.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile YellowShark.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile YellowShark.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/YellowShark1.0.0 || $(MKDIR) .tmp/YellowShark1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/YellowShark1.0.0/ && $(COPY_FILE) --parents mainwindow.h pcap_analyse.h paquet.h sendpacketwindow.h tools.h filterwindow.h live_analyse.h .tmp/YellowShark1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp pcap_analyse.cpp paquet.cpp sendpacketwindow.cpp tools.cpp filterwindow.cpp live_analyse.cpp .tmp/YellowShark1.0.0/ && $(COPY_FILE) --parents mainwindow.ui sendpacketwindow.ui filterwindow.ui .tmp/YellowShark1.0.0/ && (cd `dirname .tmp/YellowShark1.0.0` && $(TAR) YellowShark1.0.0.tar YellowShark1.0.0 && $(COMPRESS) YellowShark1.0.0.tar) && $(MOVE) `dirname .tmp/YellowShark1.0.0`/YellowShark1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/YellowShark1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_pcap_analyse.cpp moc_sendpacketwindow.cpp moc_filterwindow.cpp moc_live_analyse.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_pcap_analyse.cpp moc_sendpacketwindow.cpp moc_filterwindow.cpp moc_live_analyse.cpp
moc_mainwindow.cpp: live_analyse.h \
		paquet.h \
		sendpacketwindow.h \
		filterwindow.h \
		pcap_analyse.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_pcap_analyse.cpp: paquet.h \
		pcap_analyse.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) pcap_analyse.h -o moc_pcap_analyse.cpp

moc_sendpacketwindow.cpp: sendpacketwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sendpacketwindow.h -o moc_sendpacketwindow.cpp

moc_filterwindow.cpp: filterwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) filterwindow.h -o moc_filterwindow.cpp

moc_live_analyse.cpp: paquet.h \
		live_analyse.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) live_analyse.h -o moc_live_analyse.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_sendpacketwindow.h ui_filterwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_sendpacketwindow.h ui_filterwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_sendpacketwindow.h: sendpacketwindow.ui
	/usr/bin/uic-qt4 sendpacketwindow.ui -o ui_sendpacketwindow.h

ui_filterwindow.h: filterwindow.ui
	/usr/bin/uic-qt4 filterwindow.ui -o ui_filterwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		live_analyse.h \
		paquet.h \
		sendpacketwindow.h \
		filterwindow.h \
		pcap_analyse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		live_analyse.h \
		paquet.h \
		sendpacketwindow.h \
		filterwindow.h \
		pcap_analyse.h \
		ui_mainwindow.h \
		tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

pcap_analyse.o: pcap_analyse.cpp pcap_analyse.h \
		paquet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pcap_analyse.o pcap_analyse.cpp

paquet.o: paquet.cpp tools.h \
		paquet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o paquet.o paquet.cpp

sendpacketwindow.o: sendpacketwindow.cpp sendpacketwindow.h \
		ui_sendpacketwindow.h \
		paquet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sendpacketwindow.o sendpacketwindow.cpp

tools.o: tools.cpp tools.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tools.o tools.cpp

filterwindow.o: filterwindow.cpp filterwindow.h \
		ui_filterwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o filterwindow.o filterwindow.cpp

live_analyse.o: live_analyse.cpp live_analyse.h \
		paquet.h \
		mainwindow.h \
		sendpacketwindow.h \
		filterwindow.h \
		pcap_analyse.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o live_analyse.o live_analyse.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_pcap_analyse.o: moc_pcap_analyse.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pcap_analyse.o moc_pcap_analyse.cpp

moc_sendpacketwindow.o: moc_sendpacketwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sendpacketwindow.o moc_sendpacketwindow.cpp

moc_filterwindow.o: moc_filterwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_filterwindow.o moc_filterwindow.cpp

moc_live_analyse.o: moc_live_analyse.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_live_analyse.o moc_live_analyse.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

